version: '3.4'
services:
  jnrp:
    image: nginx:latest
    volumes:
      - "./nginxconf/jnrp.conf:/etc/nginx/nginx.conf"
    networks:
      - home
      - jk
    # ports enabled for dev test only
    # ports:
      # - 8080:80

  jn-frontend:
    image: nginx:latest
    volumes:
      - "./src/publishMe/public:/usr/share/nginx/html"
    networks:
      - jk

networks:
  home:
    external: true
  jk:
    external: true